import os
import smtplib
import threading
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

print("DEBUG: Loading utils/email_service.py [v5 - secrets based]")

# ── Load credentials from Streamlit secrets or environment ────────
try:
    import streamlit as st
    GMAIL_USER     = st.secrets["GMAIL_USER"]
    GMAIL_PASSWORD = st.secrets["GMAIL_PASSWORD"]
except Exception:
    GMAIL_USER     = os.environ.get("GMAIL_USER", "")
    GMAIL_PASSWORD = os.environ.get("GMAIL_PASSWORD", "")


def send_delivery_report(recipients, subject, report_data, pdf_file=None):
    """
    Send a professional HTML/CSS delivery report with an optional PDF attachment.
    """
    print(f"DEBUG: send_delivery_report called with report_data type: {type(report_data)}")

    if not GMAIL_USER or not GMAIL_PASSWORD:
        print("ERROR: Gmail credentials not configured in Streamlit secrets.")
        return False

    msg = MIMEMultipart("alternative")
    msg["From"]    = GMAIL_USER
    msg["To"]      = ", ".join(recipients) if isinstance(recipients, list) else recipients
    msg["Subject"] = subject

    # ── HTML body ─────────────────────────────────────────────────
    try:
        html_content = f"""
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; background-color: #f4f6f8; padding: 20px; }}
                .container {{ max-width: 600px; margin: auto; background: white; padding: 20px; border-radius: 8px; }}
                .header {{ border-bottom: 3px solid #0f62fe; padding-bottom: 10px; margin-bottom: 20px; }}
                .title {{ font-size: 20px; color: #0f62fe; font-weight: bold; }}
                .section {{ margin-top: 15px; }}
                .section-title {{ font-weight: bold; color: #161616; margin-bottom: 5px; }}
                .metric {{ background: #f2f4f8; padding: 8px; border-radius: 4px; margin-bottom: 5px; font-size: 14px; }}
                .footer {{ margin-top: 20px; font-size: 11px; color: #6f6f6f; text-align: center; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header"><div class="title">IBM DeliveryIQ Report</div></div>
                <div class="section">
                    <div class="section-title">Executive Summary</div>
                    <div class="metric"><strong>Project:</strong> {report_data.get('project', 'N/A')}</div>
                    <div class="metric"><strong>Health Score:</strong> {report_data.get('health_score', 0)}/100</div>
                    <div class="metric"><strong>Risk Level:</strong> {report_data.get('risk_level', 'Unknown')}</div>
                    <div class="metric"><strong>Confidence:</strong> {report_data.get('confidence', 0)}%</div>
                </div>
                <div class="section">
                    <div class="section-title">AI Recommendation</div>
                    <div class="metric">{report_data.get('recommendation', 'No recommendation available.')}</div>
                </div>
                <div class="section">
                    <div class="section-title">Key Metrics</div>
                    <div class="metric">Team Size: {report_data.get('team_size', 'N/A')}</div>
                    <div class="metric">Duration: {report_data.get('duration', 'N/A')} weeks</div>
                    <div class="metric">Budget: ${report_data.get('budget', 0)}</div>
                    <div class="metric">Completion Rate: {report_data.get('completion_rate', 0)}%</div>
                </div>
                <div class="footer">Generated by IBM DeliveryIQ AI Engine</div>
            </div>
        </body>
        </html>
        """
        msg.attach(MIMEText(html_content, "html"))
        print("DEBUG: Attached HTML body")

    except Exception as e:
        print(f"ERROR constructing HTML body: {e}")
        msg.attach(MIMEText("Error generating report content.", "plain"))

    # ── Attach PDF (optional) ─────────────────────────────────────
    if pdf_file:
        try:
            print(f"Attaching PDF: {pdf_file}")
            with open(pdf_file, "rb") as f:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(f.read())
            encoders.encode_base64(part)
            part.add_header("Content-Disposition", f"attachment; filename={pdf_file}")
            msg.attach(part)
        except Exception as e:
            print(f"Error attaching PDF: {e}")

    # ── SMTP send ─────────────────────────────────────────────────
    try:
        server = smtplib.SMTP("smtp.gmail.com", 587, timeout=10)
        server.starttls()
        server.login(GMAIL_USER, GMAIL_PASSWORD)
        server.sendmail(GMAIL_USER, recipients, msg.as_string())
        server.quit()
        print("Email sent successfully")
        return True
    except Exception as e:
        print(f"SMTP Error: {e}")
        return False