from datetime import datetime
import re

def _clean(text):
    """Remove emoji and non-ASCII characters for PDF compatibility."""
    # Replace common emoji with plain equivalents
    replacements = {
        "✅": "[OK]", "⚠": "[!]", "❌": "[X]",
        "✔": "[OK]", "🟢": "GREEN", "🟡": "AMBER",
        "🔴": "RED", "⭐": "*", "📋": "",
        "🤖": "", "📊": "", "✨": "",
        "■": "", "□": "", "•": "-",
    }
    for emoji, plain in replacements.items():
        text = text.replace(emoji, plain)
    # Strip any remaining non-ASCII
    text = re.sub(r'[^\x00-\x7F]+', '', text)
    return text.strip()

def _wrap(text, width=90):
    """Wrap long lines to fit PDF page width."""
    words = text.split()
    lines = []
    current = ""
    for word in words:
        if len(current) + len(word) + 1 <= width:
            current = (current + " " + word).strip()
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return "\n".join(lines) if lines else text

def generate_project_report(project_data, risk_result, health):
    """
    Generate a professional IBM DeliveryIQ project risk report.
    Returns the report as a clean ASCII string suitable for PDF.
    """
    project_name = _clean(project_data.get("project_name", "Unknown Project"))
    risk_level    = _clean(risk_result.get("risk_level", "Unknown"))
    confidence    = risk_result.get("confidence", 0)
    health_score  = health.get("health_score", 0)
    rag_status    = _clean(health.get("rag_meaning", health.get("rag_status", "Unknown")))
    recommendation = _clean(_wrap(risk_result.get("recommendation", "No recommendation available.")))
    timestamp     = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Fix: use duration_weeks directly from project_data
    duration = project_data.get("duration_weeks", project_data.get("duration", "N/A"))

    report = f"""============================================================
IBM DeliveryIQ -- Project Delivery Report
============================================================
Generated : {timestamp}
Project   : {project_name}
------------------------------------------------------------

1. EXECUTIVE SUMMARY
--------------------
Overall Project Health : {health_score}/100
RAG Status             : {rag_status}
ML Risk Level          : {risk_level}
Prediction Confidence  : {confidence:.1%}

2. AI-GENERATED INSIGHTS
------------------------
Recommendation:
{recommendation}

3. RISK FACTORS IDENTIFIED
--------------------------
"""

    top_factors = risk_result.get("top_risk_factors", [])
    if top_factors:
        for factor in top_factors:
            f_name = _clean(str(factor.get("factor", "")))
            f_imp  = factor.get("importance", 0)
            f_val  = _clean(str(factor.get("value", "")))
            report += f"- {f_name}: {f_imp}% importance (Value: {f_val})\n"
    else:
        report += "- No high-priority risk factors identified at this stage.\n"

    completion = project_data.get("tasks_completed", 0) / max(project_data.get("tasks_total", 1), 1)

    report += f"""
4. PROJECT METRICS SUMMARY
--------------------------
- Team Size        : {project_data.get("team_size", "N/A")}
- Duration (Weeks) : {duration}
- Budget (USD)     : ${project_data.get("budget_usd", 0):,}
- Complexity       : {project_data.get("complexity", "N/A")}
- Budget Spent     : {project_data.get("budget_spent_pct", 0)}%
- Current Week     : {project_data.get("current_week", "N/A")}
- Completion Rate  : {completion:.1%}
- Team Experience  : {project_data.get("team_experience_avg", "N/A")}/5
- Stakeholder Eng. : {project_data.get("stakeholder_engagement", "N/A")}
- Requirements     : {project_data.get("requirements_clarity", "N/A")}

5. HEALTH DIMENSION SCORES
--------------------------
"""
    breakdown = health.get("breakdown", {})
    for dim, score in breakdown.items():
        status = "Healthy" if score >= 70 else "Warning" if score >= 50 else "Critical"
        report += f"- {_clean(dim):<22}: {score:.0f}%  [{status}]\n"

    report += """
------------------------------------------------------------
This report was generated by IBM DeliveryIQ AI Engine.
Confidential -- IBM Internal Use Only.
============================================================
"""
    return report
